USE HERNANDEZ_T3

CREATE TABLE Empleado(
	EmpleadoId int IDENTITY PRIMARY KEY NOT NULL,
	Nombre VARCHAR(300) NOT NULL,
	Apellido VARCHAR(300) NOT NULL,
	Telefono VARCHAR(11) NOT NULL,
	Direccion VARCHAR(300) NOT NULL,
	Dni VARCHAR(8) NOT NULL,

	Usuario VARCHAR(100) NOT NULL,
	Clave VARCHAR(100) NOT NULL
);

CREATE TABLE Mascota(
	MascotaId int IDENTITY PRIMARY KEY NOT NULL,
	FechaRegistro DATETIME NOT NULL,
	Nombre VARCHAR(300) NOT NULL,
	FechaNacimiento DATETIME NOT NULL,
	Sexo VARCHAR(50) NOT NULL,
	Especie VARCHAR(300) NOT NULL,
	Raza VARCHAR(300) NOT NULL,
	Tamano FLOAT NOT NULL,
	DatosParticulares VARCHAR(1500) NOT NULL,
	NombreDueño VARCHAR(300) NOT NULL,
	Direccion VARCHAR(300) NOT NULL,
	Telefono VARCHAR(300) NOT NULL,
	Email VARCHAR(300) NOT NULL
	
);